#pragma once

struct Trig
{
  double sine;
  double other;
};


module Kong {

  struct Fu
  {
    double fighter; ///< It is a fighter
    @optional boolean looser;
    @key string member;
    uint32 happy[2];
    uint32 my_array[3][2];
    Trig onometry;
  };

};
